### ISSUE TITLE
Define and implement 'GameObject' class

### ISSUE THREAD

**Issue by ghost** [eno3nt/projlab#8]
GameObjects:
-Have a mass property.
-Utilize 'enterTile'/'leaveTile' functions for interfacing with tiles on drop/pickup.
-Can be destroyed (for example, by being dropped into a pit), thus have a 'destroy()' function on their interface.

**Comment by eno3nt** [comment]
we might not need it. if we define the threshold to be the mass of 1 create, the code as it is works. only need a counter on the floor, tracking how many crates it has (for drop/pickup logic). its implemented at branch 'enemy'
