### ISSUE TITLE
Rewrite engine to utilize timer based logic.

### ISSUE THREAD

**Issue by ghost** [eno3nt/projlab#9]
Game characters must have the ability of moving around and interacting with the game world on their own, without user input.

**Comment by ghost** [comment]
-Should all characters have a timer of their own, or should they all utilize a common timer?
-Handle the edge case where two characters attempt to enter the same tile at once.

**Comment by eno3nt** [comment]
A labirintusban egy replikátor véletlenszerűen menetel

this doesnt say anything about WHEN it moves...can move after handling player input, hence no timer is needed
